-- This file is intentionally empty.
-- Database initialization is handled by sql-scripts/00-schema.sql and sql-scripts/01-init.sql
-- which are mounted into the PostgreSQL docker-entrypoint-initdb.d directory.
