package com.example.demo

import com.example.demo.config.TestProfileResolver
import jakarta.annotation.PostConstruct
import org.springframework.context.annotation.Profile
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Component
import org.springframework.test.context.ActiveProfiles

@Component
@ActiveProfiles(resolver = TestProfileResolver::class)
class TestSchemaInitializer(
    private val jdbcTemplate: JdbcTemplate
) {

    @PostConstruct
    fun init() {
        // Создаем таблицу транзакций только в тестовом профиле (H2)
        jdbcTemplate.execute(
            """
            CREATE TABLE IF NOT EXISTS meal_transaction (
              id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              transaction_hash VARCHAR(255) NOT NULL,
              meal_timestamp TIMESTAMP NOT NULL,
              student_id UUID NOT NULL,
              chef_id UUID NOT NULL,
              offline BOOLEAN NOT NULL,
              meal_type VARCHAR(50) NOT NULL
            )
            """.trimIndent()
        )
    }
}