-- 00-schema.sql
CREATE TABLE public.groups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name character varying(255) NOT NULL UNIQUE,
    curator_id uuid
);

CREATE TABLE public.users (
    id uuid PRIMARY KEY,
    encrypted_private_key text,
    father_name character varying(255) NOT NULL,
    login character varying(255) NOT NULL UNIQUE,
    name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    public_key text,
    surname character varying(255) NOT NULL,
    group_id integer
);

CREATE TABLE public.user_roles (
    user_id uuid NOT NULL,
    role character varying(255),
    CONSTRAINT user_roles_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'REGISTRATOR'::character varying, 'CHEF'::character varying, 'CURATOR'::character varying, 'STUDENT'::character varying])::text[])))
);

CREATE TABLE public.menu_items (
    id uuid PRIMARY KEY,
    date date NOT NULL,
    description text,
    name character varying(255) NOT NULL,
    photo_url character varying(255)
);

CREATE TABLE public.meal_permission (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date,
    breakfast boolean NOT NULL,
    dinner boolean NOT NULL,
    lunch boolean NOT NULL,
    is_snack_allowed boolean NOT NULL,
    is_special_allowed boolean NOT NULL,
    reason character varying(255) NOT NULL,
    assigned_by_id uuid,
    student_id uuid
);

CREATE TABLE public.meal_transaction (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offline boolean NOT NULL,
    meal_type smallint NOT NULL,
    meal_timestamp timestamp(6) without time zone NOT NULL,
    transaction_hash character varying(255) NOT NULL,
    chef_id uuid,
    student_id uuid,
    CONSTRAINT meal_transaction_meal_type_check CHECK (((meal_type >= 0) AND (meal_type <= 5)))
);

CREATE TABLE public.suspicious_transaction (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_timestamp timestamp(6) without time zone NOT NULL,
    attempt_tx_hash character varying(255),
    base_tx_hash character varying(255),
    date date NOT NULL,
    meal_type character varying(255) NOT NULL,
    reason character varying(255) NOT NULL,
    resolved boolean NOT NULL,
    resolved_at timestamp(6) without time zone,
    chef_id uuid,
    resolved_by_id uuid,
    student_id uuid NOT NULL
);

CREATE TABLE public.password_reset_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp" timestamp(6) without time zone NOT NULL,
    reset_by_id uuid,
    user_id uuid NOT NULL
);

-- Foreign Keys
ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fkq4bactcg32fd8ptafwl8l7t9u FOREIGN KEY (curator_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkemfuglprp85bh5xwhfm898ysc FOREIGN KEY (group_id) REFERENCES public.groups(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.meal_permission
    ADD CONSTRAINT fkak9h0ed161yghn4vht3g9bgoh FOREIGN KEY (student_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.meal_permission
    ADD CONSTRAINT fkdtptyi2ldbodjpcig3trbs8m FOREIGN KEY (assigned_by_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.meal_transaction
    ADD CONSTRAINT fk1v6iccgr18p9kchqojhdu1xvu FOREIGN KEY (chef_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.meal_transaction
    ADD CONSTRAINT fk2rr220y8kdvt6eyck965h7iio FOREIGN KEY (student_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.suspicious_transaction
    ADD CONSTRAINT fk9m7um6syr4awelxadsm5ldeul FOREIGN KEY (student_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.suspicious_transaction
    ADD CONSTRAINT fkbo9vefu2wkr1xkrxku0sd8o2b FOREIGN KEY (resolved_by_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.suspicious_transaction
    ADD CONSTRAINT fkrn463p2ip3gh1qgtnt1x2cplt FOREIGN KEY (chef_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.password_reset_log
    ADD CONSTRAINT fk7slyg7rlijji9hnu2f0lpj47m FOREIGN KEY (reset_by_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.password_reset_log
    ADD CONSTRAINT fkfmck77a7jsv2nk7ykm4yjf9x2 FOREIGN KEY (user_id) REFERENCES public.users(id);
