-- Create notifications table required by NotificationEntity and APIs.
-- Idempotent by design for environments where objects may already exist.

CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    message character varying(1000) NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp(6) without time zone NOT NULL DEFAULT now()
);

DO $$
BEGIN
    IF to_regclass('public.notifications') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_notifications_user'
              AND conrelid = 'public.notifications'::regclass
        )
    THEN
        ALTER TABLE public.notifications
            ADD CONSTRAINT fk_notifications_user
            FOREIGN KEY (user_id) REFERENCES public.users(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_notifications_user_created_at_desc
    ON public.notifications (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_user_is_read
    ON public.notifications (user_id, is_read);
