-- Weekly roster workflow, absence reasons, account lifecycle, chef confirmations and notification dedupe.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'account_status') THEN
        CREATE TYPE public.account_status AS ENUM ('ACTIVE', 'FROZEN_EXPELLED');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'no_meal_reason_type') THEN
        CREATE TYPE public.no_meal_reason_type AS ENUM ('EXPELLED', 'SICK_LEAVE', 'OTHER', 'MISSING_ROSTER');
    END IF;
END $$;

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS account_status public.account_status;

UPDATE public.users
SET account_status = 'ACTIVE'
WHERE account_status IS NULL;

ALTER TABLE public.users
    ALTER COLUMN account_status SET DEFAULT 'ACTIVE',
    ALTER COLUMN account_status SET NOT NULL;

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS expelled_at timestamp(6) without time zone,
    ADD COLUMN IF NOT EXISTS expelled_by_id uuid,
    ADD COLUMN IF NOT EXISTS expel_note text;

DO $$
BEGIN
    IF to_regclass('public.users') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_users_expelled_by'
              AND conrelid = 'public.users'::regclass
        )
    THEN
        ALTER TABLE public.users
            ADD CONSTRAINT fk_users_expelled_by
            FOREIGN KEY (expelled_by_id) REFERENCES public.users(id);
    END IF;
END $$;

ALTER TABLE public.meal_permission
    ADD COLUMN IF NOT EXISTS no_meal_reason_type public.no_meal_reason_type,
    ADD COLUMN IF NOT EXISTS no_meal_reason_text character varying(512),
    ADD COLUMN IF NOT EXISTS absence_from date,
    ADD COLUMN IF NOT EXISTS absence_to date,
    ADD COLUMN IF NOT EXISTS comment text;

DO $$
BEGIN
    IF to_regclass('public.meal_permission') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'ck_meal_permission_reason_required'
              AND conrelid = 'public.meal_permission'::regclass
        )
    THEN
        ALTER TABLE public.meal_permission
            ADD CONSTRAINT ck_meal_permission_reason_required
            CHECK ((breakfast OR lunch) OR no_meal_reason_type IS NOT NULL);
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('public.meal_permission') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'ck_meal_permission_absence_range'
              AND conrelid = 'public.meal_permission'::regclass
        )
    THEN
        ALTER TABLE public.meal_permission
            ADD CONSTRAINT ck_meal_permission_absence_range
            CHECK (absence_from IS NULL OR absence_to IS NULL OR absence_from <= absence_to);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.curator_week_submission (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curator_id uuid NOT NULL,
    week_start date NOT NULL,
    submitted_at timestamp(6) without time zone NOT NULL,
    last_updated_at timestamp(6) without time zone NOT NULL
);

DO $$
BEGIN
    IF to_regclass('public.curator_week_submission') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_curator_week_submission_curator'
              AND conrelid = 'public.curator_week_submission'::regclass
        )
    THEN
        ALTER TABLE public.curator_week_submission
            ADD CONSTRAINT fk_curator_week_submission_curator
            FOREIGN KEY (curator_id) REFERENCES public.users(id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_curator_week_submission_curator_week
    ON public.curator_week_submission (curator_id, week_start);

CREATE INDEX IF NOT EXISTS idx_curator_week_submission_week
    ON public.curator_week_submission (week_start);

CREATE TABLE IF NOT EXISTS public.weekly_report_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start date NOT NULL,
    report_date date NOT NULL,
    breakfast_count integer NOT NULL DEFAULT 0,
    lunch_count integer NOT NULL DEFAULT 0,
    both_count integer NOT NULL DEFAULT 0,
    finalized_at timestamp(6) without time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_weekly_report_snapshot_week_date
    ON public.weekly_report_snapshot (week_start, report_date);

CREATE INDEX IF NOT EXISTS idx_weekly_report_snapshot_week
    ON public.weekly_report_snapshot (week_start);

CREATE TABLE IF NOT EXISTS public.chef_week_confirmation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chef_id uuid NOT NULL,
    week_start date NOT NULL,
    confirmed_at timestamp(6) without time zone NOT NULL
);

DO $$
BEGIN
    IF to_regclass('public.chef_week_confirmation') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_chef_week_confirmation_chef'
              AND conrelid = 'public.chef_week_confirmation'::regclass
        )
    THEN
        ALTER TABLE public.chef_week_confirmation
            ADD CONSTRAINT fk_chef_week_confirmation_chef
            FOREIGN KEY (chef_id) REFERENCES public.users(id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_chef_week_confirmation_chef_week
    ON public.chef_week_confirmation (chef_id, week_start);

CREATE INDEX IF NOT EXISTS idx_chef_week_confirmation_week
    ON public.chef_week_confirmation (week_start);

CREATE TABLE IF NOT EXISTS public.notification_dispatch_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    dispatch_type character varying(120) NOT NULL,
    bucket_key character varying(120) NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL DEFAULT now()
);

DO $$
BEGIN
    IF to_regclass('public.notification_dispatch_log') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_notification_dispatch_log_user'
              AND conrelid = 'public.notification_dispatch_log'::regclass
        )
    THEN
        ALTER TABLE public.notification_dispatch_log
            ADD CONSTRAINT fk_notification_dispatch_log_user
            FOREIGN KEY (user_id) REFERENCES public.users(id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_notification_dispatch_user_type_bucket
    ON public.notification_dispatch_log (user_id, dispatch_type, bucket_key);

CREATE INDEX IF NOT EXISTS idx_notification_dispatch_user_type
    ON public.notification_dispatch_log (user_id, dispatch_type);
