CREATE TABLE IF NOT EXISTS public.curator_week_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curator_id uuid NOT NULL,
    week_start date NOT NULL,
    filled_cells integer NOT NULL DEFAULT 0,
    expected_cells integer NOT NULL DEFAULT 0,
    fill_status character varying(32) NOT NULL,
    locked_at timestamp(6) without time zone NOT NULL
);

DO $$
BEGIN
    IF to_regclass('public.curator_week_audit') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_curator_week_audit_curator'
              AND conrelid = 'public.curator_week_audit'::regclass
        )
    THEN
        ALTER TABLE public.curator_week_audit
            ADD CONSTRAINT fk_curator_week_audit_curator
            FOREIGN KEY (curator_id) REFERENCES public.users(id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_curator_week_audit_curator_week
    ON public.curator_week_audit (curator_id, week_start);

CREATE INDEX IF NOT EXISTS idx_curator_week_audit_week
    ON public.curator_week_audit (week_start);
