-- Push device registry, per-user push settings, enum-to-text stabilization, retention indexes.

CREATE TABLE IF NOT EXISTS public.push_device_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    platform character varying(16) NOT NULL,
    token character varying(1024) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    last_seen_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    app_version character varying(64),
    locale character varying(32),
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    updated_at timestamp(6) without time zone NOT NULL DEFAULT now()
);

DO $$
BEGIN
    IF to_regclass('public.push_device_token') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_push_device_token_user'
              AND conrelid = 'public.push_device_token'::regclass
        )
    THEN
        ALTER TABLE public.push_device_token
            ADD CONSTRAINT fk_push_device_token_user
            FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('public.push_device_token') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'ck_push_device_platform'
              AND conrelid = 'public.push_device_token'::regclass
        )
    THEN
        ALTER TABLE public.push_device_token
            ADD CONSTRAINT ck_push_device_platform
            CHECK (platform IN ('ANDROID', 'IOS'));
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_push_device_platform_token
    ON public.push_device_token (platform, token);

CREATE INDEX IF NOT EXISTS idx_push_device_user_active
    ON public.push_device_token (user_id, active);

CREATE INDEX IF NOT EXISTS idx_push_device_last_seen
    ON public.push_device_token (last_seen_at);

CREATE INDEX IF NOT EXISTS idx_push_device_active_updated
    ON public.push_device_token (active, updated_at);

CREATE TABLE IF NOT EXISTS public.user_notification_settings (
    user_id uuid PRIMARY KEY,
    push_enabled boolean NOT NULL DEFAULT true,
    updated_at timestamp(6) without time zone NOT NULL DEFAULT now()
);

DO $$
BEGIN
    IF to_regclass('public.user_notification_settings') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_user_notification_settings_user'
              AND conrelid = 'public.user_notification_settings'::regclass
        )
    THEN
        ALTER TABLE public.user_notification_settings
            ADD CONSTRAINT fk_user_notification_settings_user
            FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;

INSERT INTO public.user_notification_settings (user_id, push_enabled, updated_at)
SELECT id, true, now()
FROM public.users
ON CONFLICT (user_id) DO NOTHING;

-- Convert users.account_status from PostgreSQL enum to string to avoid enum binding issues.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'users'
          AND column_name = 'account_status'
    ) THEN
        BEGIN
            ALTER TABLE public.users
                ALTER COLUMN account_status DROP DEFAULT;
        EXCEPTION
            WHEN others THEN
                NULL;
        END;
        BEGIN
            ALTER TABLE public.users
                ALTER COLUMN account_status TYPE character varying(32)
                USING account_status::text;
        EXCEPTION
            WHEN others THEN
                -- Column might already be text/varchar in target environment.
                NULL;
        END;
    END IF;
END $$;

UPDATE public.users
SET account_status = 'ACTIVE'
WHERE account_status IS NULL OR trim(account_status) = '';

ALTER TABLE public.users
    ALTER COLUMN account_status SET DEFAULT 'ACTIVE',
    ALTER COLUMN account_status SET NOT NULL;

ALTER TABLE public.users
    DROP CONSTRAINT IF EXISTS ck_users_account_status;

ALTER TABLE public.users
    ADD CONSTRAINT ck_users_account_status
    CHECK (account_status IN ('ACTIVE', 'FROZEN_EXPELLED'));

-- Convert meal_permission.no_meal_reason_type from enum to string for consistency.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'meal_permission'
          AND column_name = 'no_meal_reason_type'
    ) THEN
        BEGIN
            ALTER TABLE public.meal_permission
                ALTER COLUMN no_meal_reason_type TYPE character varying(32)
                USING no_meal_reason_type::text;
        EXCEPTION
            WHEN others THEN
                -- Column might already be text/varchar in target environment.
                NULL;
        END;
    END IF;
END $$;

DO $$
BEGIN
    BEGIN
        DROP TYPE IF EXISTS public.account_status;
    EXCEPTION
        WHEN others THEN
            NULL;
    END;
END $$;

DO $$
BEGIN
    BEGIN
        DROP TYPE IF EXISTS public.no_meal_reason_type;
    EXCEPTION
        WHEN others THEN
            NULL;
    END;
END $$;

ALTER TABLE public.meal_permission
    DROP CONSTRAINT IF EXISTS ck_meal_permission_no_meal_reason_type;

ALTER TABLE public.meal_permission
    ADD CONSTRAINT ck_meal_permission_no_meal_reason_type
    CHECK (
        no_meal_reason_type IS NULL
        OR no_meal_reason_type IN ('EXPELLED', 'SICK_LEAVE', 'OTHER', 'MISSING_ROSTER')
    );

-- Indexes for scheduled retention cleanup.
CREATE INDEX IF NOT EXISTS idx_notifications_created_at
    ON public.notifications (created_at);

CREATE INDEX IF NOT EXISTS idx_meal_tx_timestamp
    ON public.meal_transaction (meal_timestamp);

CREATE INDEX IF NOT EXISTS idx_meal_permission_date
    ON public.meal_permission (date);

CREATE INDEX IF NOT EXISTS idx_weekly_report_snapshot_report_date
    ON public.weekly_report_snapshot (report_date);

CREATE INDEX IF NOT EXISTS idx_curator_week_audit_locked_at
    ON public.curator_week_audit (locked_at);

CREATE INDEX IF NOT EXISTS idx_curator_week_submission_last_updated_at
    ON public.curator_week_submission (last_updated_at);

CREATE INDEX IF NOT EXISTS idx_chef_week_confirmation_confirmed_at
    ON public.chef_week_confirmation (confirmed_at);

CREATE INDEX IF NOT EXISTS idx_notification_dispatch_log_sent_at
    ON public.notification_dispatch_log (sent_at);

CREATE INDEX IF NOT EXISTS idx_password_reset_log_timestamp
    ON public.password_reset_log ("timestamp");

CREATE INDEX IF NOT EXISTS idx_suspicious_tx_resolved_resolved_at
    ON public.suspicious_transaction (resolved, resolved_at);
